In [6]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np
import pandas as pd

In [2]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [3]:
l=SVC(C=1e5,kernel='linear')
l.fit(X,y)

SVC(C=100000.0, kernel='linear')

In [5]:
l

SVC(C=100000.0, kernel='linear')

In [4]:
print('w = ',l.coef_)
print('b = ',l.intercept_)
print('Indices of support vectors= ',l.support_)
print('Support vectors= ')
print(l.support_vectors_)
print('No. of support vectors fro each class= ',l.n_support_)
print('coefficient of support vectors in decision function= ',np.abs(l.dual_coef_))


w =  [[ 0.25 -0.25]]
b =  [-0.75]
Indices of support vectors=  [2 3]
Support vectors= 
[[ 2.  3.]
 [ 6. -1.]]
No. of support vectors fro each class=  [1 1]
coefficient of support vectors in decision function=  [[0.0625 0.0625]]


In [7]:
data=pd.read_csv('/content/drive/MyDrive/ML LABS/glass.csv')
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [8]:
x=data.drop('Type',axis=1)
y=data.Type


In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [10]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [11]:
print(linear.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [7.10000e+01 1.51574e+00 1.48600e+01 3.67000e+00 1.74000e+00 7.18700e+01
  1.60000e-01 7.36000e+00 0.00000e+00 1.20000e-01]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.30000e+01 1.51593e+00 1.30900e+01 3.59000e+00 1.52000e+00 7.31000e+01
  6.70000e-01 7.83000e+00 0.00000e+00 0.00000e+00]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.61000e+02 1.51832e+00 1.33300e+01 3.34000e+00 1.54000e+00 7.21400e+01
  5.60000e-01 8.99000e+00 0.00000e+00 0.00000e+00]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.76000e+02 1.52119e+00 1.29700e+01 3.30000e-01 1.51000e+00 7.33900e+01
  1.30000e-01 1.12700e+01 0.00000e+00 2.80000e-01]


In [12]:
print(linear.n_support_)

[1 3 2 4 4 2]


In [13]:
y_pred=linear.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


1.0


In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[18  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0  7  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  4  0]
 [ 0  0  0  0  0 11]]


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        20
           3       1.00      1.00      1.00         7
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00        11

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [17]:
#with different kernels
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)


SVC()

In [18]:

y_pred1=model1.predict(x_test)

y_pred2=model2.predict(x_test)

y_pred3=model3.predict(x_test)